export const FETCH_ROOTS = "@@internal/FETCH_ROOTS";
export const FETCH_ROOTS_FAILURE = "@@internal/FETCH_ROOTS_FAILURE";
export const FETCH_ROOTS_SUCCESS = "@@internal/FETCH_ROOTS_SUCCESS";

export const FETCH_INVIDVIDUAL_ROOT = "@@internal/FETCH_INVIDVIDUAL_ROOT";
export const FETCH_INVIDVIDUAL_ROOT_SUCCESS =
  "@@internal/FETCH_INVIDVIDUAL_ROOT_SUCCESS";
export const FETCH_INVIDVIDUAL_ROOT_FAILURE =
  "@@internal/FETCH_INVIDVIDUAL_ROOT_FAILURE";

export const FETCH_ARRAY_ROOT = "@@internal/FETCH_ARRAY_ROOT";
export const FETCH_ARRAY_ROOT_PENDING = "@@internal/FETCH_ARRAY_ROOT_PENDING";
export const FETCH_ARRAY_ROOT_SUCCESS = "@@internal/FETCH_ARRAY_ROOT_SUCCESS";
export const FETCH_ARRAY_ROOT_ERROR = "@@internall/FETCH_ARRAY_ROOT_ERROR";
