export const FETCH_ROOTS = 'FETCH_ROOTS';
export const FETCH_ROOTS_FAILURE = 'FETCH_ROOTS_FAILURE';
export const FETCH_ROOTS_SUCCESS = 'FETCH_ROOTS_SUCCESS';
export const FETCH_LOADING = 'FETCH_LOADING';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';